@tool
extends EditorScript
## Seed generator for the PatternDB showcase database. Run from the editor:
## File → Run (Ctrl/Cmd+Shift+X) with this script open. Regenerates
## res://sample_rpg_database.pdb with a broad tour of PatternDB features:
## enums, constants (incl. vector/color values), multi-level inheritance,
## every common and exotic field type, hierarchical dot-path tags, and a
## web of cross-instance references (quest chains, skill/dialogue trees,
## recipes, loot tables, faction relations, merchant stock).

const OUT_PATH := "res://sample_rpg_database.pdb"

func _run() -> void:
	var db := PatternDatabaseFile.new()
	db.ensure_uid()
	db.version = 3
	db.meta_data = {
		"name": "RPG Showcase",
		"note": "Generated by build_showcase_sample.gd — a feature tour, not a real game.",
		"export_dir": "res://data/generated",
		"enum_class": "enums",
		"const_class": "consts",
	}

	_build_enums(db)
	_build_consts(db)
	_build_definitions(db)
	_build_instances(db)

	var err := _write_pdb(db)
	if err == OK:
		print("[PatternDB] Wrote %s — %d patterns." % [OUT_PATH, db.patterns.size()])
		if Engine.is_editor_hint():
			EditorInterface.get_resource_filesystem().scan()
	else:
		push_error("[PatternDB] Save failed (error %d)." % err)

func _write_pdb(db: PatternDatabaseFile) -> Error:
	var saver := PdbSaver.new()
	var err: Error = saver._save(db, OUT_PATH, 0)
	if err == OK:
		return OK
	var tmp := "user://.__pdb_showcase_tmp.tres"
	var old_path := db.resource_path
	db.resource_path = tmp
	err = ResourceSaver.save(db, tmp)
	db.resource_path = old_path
	if err != OK:
		return err
	var text := FileAccess.get_file_as_string(tmp)
	if text.is_empty():
		return ERR_FILE_CANT_READ
	var dst := FileAccess.open(OUT_PATH, FileAccess.WRITE)
	if dst == null:
		return FileAccess.get_open_error()
	dst.store_string(text)
	dst.close()
	if FileAccess.file_exists(tmp):
		DirAccess.remove_absolute(ProjectSettings.globalize_path(tmp))
	return OK

func _build_enums(db: PatternDatabaseFile) -> void:
	_add(db, _enum(&"ItemRarity", "items", "Rarity tiers driving drop chance, tint, and value.", {"COMMON": 0, "UNCOMMON": 1, "RARE": 2, "EPIC": 3, "LEGENDARY": 4, "MYTHIC": 5}))
	_add(db, _enum(&"DamageType", "combat", "Elemental and physical damage schools.", {"PHYSICAL": 0, "FIRE": 1, "FROST": 2, "LIGHTNING": 3, "SHADOW": 4, "HOLY": 5, "ARCANE": 6, "POISON": 7, "TRUE": 8}))
	_add(db, _enum(&"EquipSlot", "items", "Where a piece of gear is worn.", {"WEAPON": 0, "OFFHAND": 1, "HEAD": 2, "CHEST": 3, "HANDS": 4, "LEGS": 5, "FEET": 6, "RING": 7, "AMULET": 8, "BACK": 9}))
	_add(db, _enum(&"CharacterClass", "characters", "Playable and NPC archetypes.", {"WARRIOR": 0, "MAGE": 1, "ROGUE": 2, "CLERIC": 3, "RANGER": 4, "DRUID": 5, "NECROMANCER": 6}))
	_add(db, _enum(&"StatusEffect", "combat", "Buffs and debuffs applied in combat.", {"NONE": 0, "BURNING": 1, "FROZEN": 2, "POISONED": 3, "STUNNED": 4, "BLESSED": 5, "REGEN": 6, "SHIELDED": 7, "SILENCED": 8, "HASTED": 9, "SLOWED": 10}))
	_add(db, _enum(&"QuestType", "world", "Categorises quests for the journal.", {"MAIN": 0, "SIDE": 1, "BOUNTY": 2, "REPEATABLE": 3, "EVENT": 4}))
	_add(db, _enum(&"Faction", "world", "Allegiance groups used for reputation and hostility.", {"ALLIANCE": 0, "HORDE": 1, "NEUTRAL": 2, "BANDIT": 3, "MONSTER": 4, "MERCHANT_GUILD": 5, "ARCANE_ORDER": 6}))
	_add(db, _enum(&"Biome", "world", "Environmental theme of a zone.", {"FOREST": 0, "DESERT": 1, "TUNDRA": 2, "VOLCANO": 3, "DUNGEON": 4, "SWAMP": 5, "CAVERN": 6, "CITY": 7, "COAST": 8}))
	_add(db, _enum(&"WeaponType", "items", "Physical form of a weapon; drives animations.", {"SWORD": 0, "AXE": 1, "MACE": 2, "DAGGER": 3, "SPEAR": 4, "BOW": 5, "CROSSBOW": 6, "STAFF": 7, "WAND": 8}))
	_add(db, _enum(&"ArmorMaterial", "items", "Material class of armor; affects weight and resist.", {"CLOTH": 0, "LEATHER": 1, "MAIL": 2, "PLATE": 3, "DRAGONSCALE": 4}))
	_add(db, _enum(&"AIBehavior", "world", "Default combat/idle behaviour for an enemy.", {"PASSIVE": 0, "DEFENSIVE": 1, "AGGRESSIVE": 2, "PATROL": 3, "AMBUSH": 4, "CASTER": 5}))
	_add(db, _enum(&"TimeOfDay", "world", "Ambient time bracket that gates events and spawns.", {"DAWN": 0, "DAY": 1, "DUSK": 2, "NIGHT": 3}))
	_add(db, _enum(&"MerchantType", "world", "What a vendor stocks and buys.", {"GENERAL": 0, "BLACKSMITH": 1, "ALCHEMIST": 2, "JEWELER": 3, "FENCE": 4}))
	_add(db, _enum(&"SkillCategory", "characters", "Branch of the skill tree a node belongs to.", {"OFFENSE": 0, "DEFENSE": 1, "UTILITY": 2, "PASSIVE": 3}))
func _build_consts(db: PatternDatabaseFile) -> void:
	_add(db, _const(&"GameBalance", "config", "Core level/health/mana tuning.", {"base_health": 100, "base_mana": 50, "level_cap": 60, "exp_curve_base": 1.15, "crit_multiplier": 2.0}))
	_add(db, _const(&"DropRates", "config", "Percent chance per rarity band.", {"common": 55.0, "uncommon": 28.0, "rare": 12.0, "epic": 4.0, "legendary": 1.0}))
	_add(db, _const(&"Economy", "config", "Gold, vendor and repair economy.", {"starting_gold": 50, "vendor_markup": 1.5, "repair_cost_per_point": 2}))
	_add(db, _const(&"CombatTuning", "config", "Armor, dodge and block formulas.", {"armor_k": 0.06, "dodge_cap": 0.4, "block_value": 0.25}))
	_add(db, _const(&"WorldSettings", "config", "World tuning constants.", {"gravity": -9.8, "tile_size": 64, "day_length_sec": 1200.0}))
	_add(db, _const(&"UITheme", "config", "Named UI colors (Color-valued constants).", {"accent": Color(0.36, 0.62, 1.0), "danger": Color(0.85, 0.24, 0.24), "gold": Color(0.95, 0.78, 0.25)}))
	_add(db, _const(&"BuildInfo", "config", "String-valued build metadata.", {"version": "1.0.0", "channel": "beta", "codename": "Emberfall"}))
	_add(db, _const(&"CameraRig", "config", "Camera defaults.", {"fov": 68.0, "distance": 8.0, "pitch_min": -40.0, "pitch_max": 20.0}))

func _build_definitions(db: PatternDatabaseFile) -> void:
	_add(db, _def(&"Ability", "combat", "An active skill an actor can use.", "Resource", "Play", [
		_field(&"name", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "Display name.", true),
		_field(&"description", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "Tooltip text.", false),
		_field(&"damage_type", TYPE_INT, PROPERTY_HINT_ENUM, "DamageType", "Combat", "Element used for resist checks.", false),
		_field(&"power", TYPE_FLOAT, PROPERTY_HINT_NONE, "", "Combat", "Base magnitude.", false, 10.0),
		_field(&"mana_cost", TYPE_INT, PROPERTY_HINT_NONE, "", "Combat", "", false, 0),
		_field(&"cooldown", TYPE_FLOAT, PROPERTY_HINT_NONE, "", "Combat", "", false, 1.0),
		_field(&"aoe_radius", TYPE_FLOAT, PROPERTY_HINT_NONE, "", "Combat", "0 = single target.", false),
		_field(&"required_class", TYPE_INT, PROPERTY_HINT_ENUM, "CharacterClass", "Requirements", "", false),
		_field(&"applies_status", TYPE_INT, PROPERTY_HINT_ENUM, "StatusEffect", "Combat", "", false),
		_field(&"scaling", TYPE_DICTIONARY, PROPERTY_HINT_NONE, "stat", "Combat", "Per-stat scaling coefficients (nested dict).", false),
	]))
	_add(db, _def(&"Item", "items", "Base item every pickup inherits from.", "Resource", "Object", [
		_field(&"name", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "Display name.", true),
		_field(&"description", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "", false),
		_field(&"rarity", TYPE_INT, PROPERTY_HINT_ENUM, "ItemRarity", "Basic", "", false),
		_field(&"value", TYPE_INT, PROPERTY_HINT_NONE, "", "Economy", "Base vendor value in gold.", false),
		_field(&"weight", TYPE_FLOAT, PROPERTY_HINT_NONE, "", "Basic", "", false, 1.0),
		_field(&"is_unique", TYPE_BOOL, PROPERTY_HINT_NONE, "", "Basic", "", false),
		_field(&"icon", TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Texture2D", "Presentation", "Engine resource reference (stored as a res:// path).", false),
		_field(&"tint", TYPE_COLOR, PROPERTY_HINT_NONE, "", "Presentation", "", false),
	]))
	_add(db, _def(&"Weapon", "items", "A wieldable weapon.", "Item", "BoxMesh", [
		_field(&"weapon_type", TYPE_INT, PROPERTY_HINT_ENUM, "WeaponType", "Combat", "", false),
		_field(&"damage_type", TYPE_INT, PROPERTY_HINT_ENUM, "DamageType", "Combat", "", false),
		_field(&"base_damage", TYPE_FLOAT, PROPERTY_HINT_NONE, "", "Combat", "", false, 5.0),
		_field(&"attack_speed", TYPE_FLOAT, PROPERTY_HINT_NONE, "", "Combat", "", false, 1.0),
		_field(&"two_handed", TYPE_BOOL, PROPERTY_HINT_NONE, "", "Combat", "", false),
		_field(&"granted_ability", TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Ability", "Effects", "Cross-instance reference to an Ability.", false),
	]))
	_add(db, _def(&"RangedWeapon", "items", "A weapon that fires projectiles (3rd inheritance level).", "Weapon", "Path2D", [
		_field(&"range", TYPE_FLOAT, PROPERTY_HINT_NONE, "", "Ranged", "", false, 20.0),
		_field(&"projectile_speed", TYPE_FLOAT, PROPERTY_HINT_NONE, "", "Ranged", "", false, 30.0),
		_field(&"spread_degrees", TYPE_FLOAT, PROPERTY_HINT_NONE, "", "Ranged", "Cone spread in degrees.", false, 2.0),
		_field(&"ammo_item", TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Item", "Ranged", "Consumed ammunition (item reference).", false),
	]))
	_add(db, _def(&"Armor", "items", "Wearable protection.", "Item", "MeshInstance3D", [
		_field(&"slot", TYPE_INT, PROPERTY_HINT_ENUM, "EquipSlot", "Basic", "", false),
		_field(&"material", TYPE_INT, PROPERTY_HINT_ENUM, "ArmorMaterial", "Basic", "", false),
		_field(&"armor_value", TYPE_INT, PROPERTY_HINT_NONE, "", "Defense", "", false),
		_field(&"resistances", TYPE_DICTIONARY, PROPERTY_HINT_NONE, "DamageType", "Defense", "Element -> reduction fraction (nested dict).", false),
		_field(&"set_pieces", TYPE_ARRAY, PROPERTY_HINT_ARRAY_TYPE, "Armor", "Sets", "Other Armor instances in the same set.", false),
	]))
	_add(db, _def(&"Consumable", "items", "Single-use item.", "Item", "Timer", [
		_field(&"heal_amount", TYPE_INT, PROPERTY_HINT_NONE, "", "Effect", "", false),
		_field(&"restores_mana", TYPE_INT, PROPERTY_HINT_NONE, "", "Effect", "", false),
		_field(&"applies_status", TYPE_INT, PROPERTY_HINT_ENUM, "StatusEffect", "Effect", "", false),
		_field(&"duration", TYPE_FLOAT, PROPERTY_HINT_NONE, "", "Effect", "Effect duration in seconds.", false),
		_field(&"stack_size", TYPE_INT, PROPERTY_HINT_NONE, "", "Basic", "", false, 1),
	]))
	_add(db, _def(&"StatusEffectDef", "combat", "Data for a buff/debuff.", "Resource", "Time", [
		_field(&"name", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "", true),
		_field(&"effect", TYPE_INT, PROPERTY_HINT_ENUM, "StatusEffect", "Basic", "", false),
		_field(&"tick_damage", TYPE_FLOAT, PROPERTY_HINT_NONE, "", "Combat", "", false),
		_field(&"duration", TYPE_FLOAT, PROPERTY_HINT_NONE, "", "Combat", "", false, 3.0),
		_field(&"stacks", TYPE_BOOL, PROPERTY_HINT_NONE, "", "Combat", "", false),
		_field(&"modifiers", TYPE_DICTIONARY, PROPERTY_HINT_NONE, "", "Combat", "Flat stat modifiers while active.", false),
	]))
	_add(db, _def(&"SkillNode", "characters", "A node in a branching skill tree.", "Resource", "GraphNode", [
		_field(&"name", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "", true),
		_field(&"category", TYPE_INT, PROPERTY_HINT_ENUM, "SkillCategory", "Basic", "", false),
		_field(&"cost", TYPE_INT, PROPERTY_HINT_NONE, "", "Basic", "", false, 1),
		_field(&"prerequisites", TYPE_ARRAY, PROPERTY_HINT_ARRAY_TYPE, "SkillNode", "Tree", "Self-referential: nodes required first.", false),
		_field(&"grants_ability", TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Ability", "Grants", "", false),
	]))
	_add(db, _def(&"Enemy", "world", "A hostile actor.", "Resource", "Enemy", [
		_field(&"name", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "", true),
		_field(&"level", TYPE_INT, PROPERTY_HINT_NONE, "", "Stats", "", false, 1),
		_field(&"health", TYPE_INT, PROPERTY_HINT_NONE, "", "Stats", "", false, 10),
		_field(&"faction", TYPE_INT, PROPERTY_HINT_ENUM, "Faction", "Basic", "", false),
		_field(&"behavior", TYPE_INT, PROPERTY_HINT_ENUM, "AIBehavior", "AI", "", false),
		_field(&"is_boss", TYPE_BOOL, PROPERTY_HINT_NONE, "", "Basic", "", false),
		_field(&"abilities", TYPE_ARRAY, PROPERTY_HINT_ARRAY_TYPE, "Ability", "Combat", "", false),
		_field(&"loot_table", TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "LootTable", "Rewards", "", false),
		_field(&"tint", TYPE_COLOR, PROPERTY_HINT_NONE, "", "Presentation", "", false),
	]))
	_add(db, _def(&"Character", "characters", "A playable or party character.", "Resource", "Player", [
		_field(&"name", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "", true),
		_field(&"char_class", TYPE_INT, PROPERTY_HINT_ENUM, "CharacterClass", "Basic", "", false),
		_field(&"starting_weapon", TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Weapon", "Loadout", "", false),
		_field(&"starting_abilities", TYPE_ARRAY, PROPERTY_HINT_ARRAY_TYPE, "Ability", "Loadout", "", false),
		_field(&"skills", TYPE_ARRAY, PROPERTY_HINT_ARRAY_TYPE, "SkillNode", "Progression", "", false),
		_field(&"stats", TYPE_DICTIONARY, PROPERTY_HINT_NONE, "", "Stats", "Named base stats (nested dict; try the Table nesting slider).", false),
	]))
	_add(db, _def(&"LootTable", "world", "Weighted drop table.", "Resource", "AnimationTrackList", [
		_field(&"name", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "", true),
		_field(&"entries", TYPE_DICTIONARY, PROPERTY_HINT_NONE, "", "Drops", "Item id -> weight (nested dict).", false),
		_field(&"guaranteed", TYPE_ARRAY, PROPERTY_HINT_ARRAY_TYPE, "Item", "Drops", "", false),
		_field(&"gold_min", TYPE_INT, PROPERTY_HINT_NONE, "", "Drops", "", false, 0),
		_field(&"gold_max", TYPE_INT, PROPERTY_HINT_NONE, "", "Drops", "", false, 0),
		_field(&"rolls", TYPE_INT, PROPERTY_HINT_NONE, "", "Drops", "", false, 1),
	]))
	_add(db, _def(&"Recipe", "world", "A crafting recipe.", "Resource", "Tools", [
		_field(&"name", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "", true),
		_field(&"result", TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Item", "Craft", "", false),
		_field(&"ingredients", TYPE_ARRAY, PROPERTY_HINT_ARRAY_TYPE, "Item", "Craft", "", false),
		_field(&"quantities", TYPE_DICTIONARY, PROPERTY_HINT_NONE, "", "Craft", "Ingredient id -> count (nested dict).", false),
		_field(&"station", TYPE_INT, PROPERTY_HINT_ENUM, "MerchantType", "Craft", "", false),
		_field(&"craft_time", TYPE_FLOAT, PROPERTY_HINT_NONE, "", "Craft", "", false, 2.0),
	]))
	_add(db, _def(&"Merchant", "world", "A vendor NPC.", "Resource", "FileDialog", [
		_field(&"name", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "", true),
		_field(&"merchant_type", TYPE_INT, PROPERTY_HINT_ENUM, "MerchantType", "Basic", "", false),
		_field(&"faction", TYPE_INT, PROPERTY_HINT_ENUM, "Faction", "Basic", "", false),
		_field(&"inventory", TYPE_ARRAY, PROPERTY_HINT_ARRAY_TYPE, "Item", "Stock", "", false),
		_field(&"price_overrides", TYPE_DICTIONARY, PROPERTY_HINT_NONE, "", "Stock", "Item id -> fixed price (nested dict).", false),
		_field(&"open_hour", TYPE_INT, PROPERTY_HINT_NONE, "", "Schedule", "", false, 8),
		_field(&"close_hour", TYPE_INT, PROPERTY_HINT_NONE, "", "Schedule", "", false, 20),
	]))
	_add(db, _def(&"FactionRelation", "world", "Standing between two factions.", "Resource", "Signals", [
		_field(&"faction_a", TYPE_INT, PROPERTY_HINT_ENUM, "Faction", "Basic", "", false),
		_field(&"faction_b", TYPE_INT, PROPERTY_HINT_ENUM, "Faction", "Basic", "", false),
		_field(&"standing", TYPE_INT, PROPERTY_HINT_NONE, "", "Relation", "-100 hostile .. +100 allied.", false),
		_field(&"at_war", TYPE_BOOL, PROPERTY_HINT_NONE, "", "Relation", "", false),
		_field(&"modifiers", TYPE_DICTIONARY, PROPERTY_HINT_NONE, "", "Relation", "Contextual standing modifiers.", false),
	]))
	_add(db, _def(&"Quest", "world", "A journal quest.", "Resource", "Bookmark", [
		_field(&"name", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "", true),
		_field(&"quest_type", TYPE_INT, PROPERTY_HINT_ENUM, "QuestType", "Basic", "", false),
		_field(&"giver", TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Enemy", "Flow", "", false),
		_field(&"prerequisite", TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Quest", "Flow", "Self-referential quest chain.", false),
		_field(&"reward_item", TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Item", "Rewards", "", false),
		_field(&"reward_gold", TYPE_INT, PROPERTY_HINT_NONE, "", "Rewards", "", false),
		_field(&"objectives", TYPE_PACKED_STRING_ARRAY, PROPERTY_HINT_NONE, "", "Flow", "", false),
		_field(&"stage_flags", TYPE_DICTIONARY, PROPERTY_HINT_NONE, "", "Flow", "Objective id -> completed bool.", false),
		_field(&"turn_in_biome", TYPE_INT, PROPERTY_HINT_ENUM, "Biome", "Flow", "", false),
	]))
	_add(db, _def(&"DialogueNode", "world", "One line in a branching conversation.", "Resource", "RichTextLabel", [
		_field(&"speaker", TYPE_STRING_NAME, PROPERTY_HINT_NONE, "", "Basic", "Speaker id (StringName field).", false),
		_field(&"text", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "", true),
		_field(&"mood", TYPE_INT, PROPERTY_HINT_ENUM, "StatusEffect", "Basic", "", false),
		_field(&"responses", TYPE_DICTIONARY, PROPERTY_HINT_NONE, "", "Flow", "Reply text -> next node id (nested dict).", false),
		_field(&"next_nodes", TYPE_ARRAY, PROPERTY_HINT_ARRAY_TYPE, "DialogueNode", "Flow", "Self-referential dialogue tree.", false),
		_field(&"portrait", TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Texture2D", "Presentation", "", false),
	]))
	_add(db, _def(&"Achievement", "meta", "An unlockable achievement.", "Resource", "Favorites", [
		_field(&"title", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "", true),
		_field(&"description", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "", false),
		_field(&"points", TYPE_INT, PROPERTY_HINT_NONE, "", "Basic", "", false, 10),
		_field(&"hidden", TYPE_BOOL, PROPERTY_HINT_NONE, "", "Basic", "", false),
		_field(&"reward_item", TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Item", "Rewards", "", false),
		_field(&"required_quest", TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Quest", "Unlock", "", false),
	]))
	_add(db, _def(&"Zone", "world", "A playable area of the map.", "Resource", "Environment", [
		_field(&"name", TYPE_STRING, PROPERTY_HINT_NONE, "", "Basic", "", true),
		_field(&"biome", TYPE_INT, PROPERTY_HINT_ENUM, "Biome", "Basic", "", false),
		_field(&"min_level", TYPE_INT, PROPERTY_HINT_NONE, "", "Difficulty", "", false, 1),
		_field(&"max_level", TYPE_INT, PROPERTY_HINT_NONE, "", "Difficulty", "", false, 10),
		_field(&"merchants", TYPE_ARRAY, PROPERTY_HINT_ARRAY_TYPE, "Merchant", "Content", "", false),
		_field(&"ambient_color", TYPE_COLOR, PROPERTY_HINT_NONE, "", "Presentation", "", false),
	]))

func _build_instances(db: PatternDatabaseFile) -> void:
	_add(db, _inst(&"Slash", &"Ability", ["dps", "melee", "starter"], {"name": "Slash", "description": "A quick sword strike.", "damage_type": 0, "power": 15.0, "mana_cost": 0, "cooldown": 0.5, "aoe_radius": 0.0, "required_class": 0, "applies_status": 0, "scaling": {"strength": 0.6}}))
	_add(db, _inst(&"Cleave", &"Ability", ["dps", "melee", "aoe"], {"name": "Cleave", "description": "Sweeps all enemies in front.", "damage_type": 0, "power": 26.0, "mana_cost": 8, "cooldown": 3.0, "aoe_radius": 3.5, "required_class": 0, "applies_status": 0, "scaling": {"strength": 0.9}}))
	_add(db, _inst(&"ShieldBash", &"Ability", ["tank", "stun"], {"name": "Shield Bash", "description": "Stuns a single target.", "damage_type": 0, "power": 12.0, "mana_cost": 6, "cooldown": 5.0, "aoe_radius": 0.0, "required_class": 0, "applies_status": 4, "scaling": {"strength": 0.4}}))
	_add(db, _inst(&"Fireball", &"Ability", ["dps", "fire", "aoe"], {"name": "Fireball", "description": "Hurls an explosive ball of flame.", "damage_type": 1, "power": 40.0, "mana_cost": 20, "cooldown": 3.0, "aoe_radius": 4.0, "required_class": 1, "applies_status": 1, "scaling": {"intellect": 1.1}}))
	_add(db, _inst(&"Frostbolt", &"Ability", ["dps", "frost"], {"name": "Frostbolt", "description": "A shard of ice that chills foes.", "damage_type": 2, "power": 28.0, "mana_cost": 12, "cooldown": 1.5, "aoe_radius": 0.0, "required_class": 1, "applies_status": 2, "scaling": {"intellect": 0.8}}))
	_add(db, _inst(&"ArcaneMissiles", &"Ability", ["dps", "arcane"], {"name": "Arcane Missiles", "description": "A barrage of homing bolts.", "damage_type": 6, "power": 34.0, "mana_cost": 18, "cooldown": 2.0, "aoe_radius": 0.0, "required_class": 1, "applies_status": 0, "scaling": {"intellect": 1.0}}))
	_add(db, _inst(&"Blizzard", &"Ability", ["dps", "frost", "aoe", "ultimate"], {"name": "Blizzard", "description": "A storm of ice over a wide area.", "damage_type": 2, "power": 55.0, "mana_cost": 40, "cooldown": 10.0, "aoe_radius": 6.0, "required_class": 1, "applies_status": 10, "scaling": {"intellect": 1.4}}))
	_add(db, _inst(&"Heal", &"Ability", ["healer", "holy"], {"name": "Heal", "description": "Restores health to an ally.", "damage_type": 5, "power": 35.0, "mana_cost": 18, "cooldown": 2.0, "aoe_radius": 0.0, "required_class": 3, "applies_status": 6, "scaling": {"wisdom": 1.2}}))
	_add(db, _inst(&"Smite", &"Ability", ["dps", "holy"], {"name": "Smite", "description": "Holy damage that burns the wicked.", "damage_type": 5, "power": 30.0, "mana_cost": 15, "cooldown": 2.5, "aoe_radius": 0.0, "required_class": 3, "applies_status": 0, "scaling": {"wisdom": 0.8}}))
	_add(db, _inst(&"Bless", &"Ability", ["support", "buff"], {"name": "Bless", "description": "Grants a protective blessing.", "damage_type": 5, "power": 0.0, "mana_cost": 25, "cooldown": 12.0, "aoe_radius": 5.0, "required_class": 3, "applies_status": 5, "scaling": {"wisdom": 0.5}}))
	_add(db, _inst(&"Backstab", &"Ability", ["dps", "melee", "stealth"], {"name": "Backstab", "description": "Massive damage from stealth.", "damage_type": 0, "power": 55.0, "mana_cost": 10, "cooldown": 4.0, "aoe_radius": 0.0, "required_class": 2, "applies_status": 0, "scaling": {"agility": 1.3}}))
	_add(db, _inst(&"PoisonBlade", &"Ability", ["dps", "poison", "dot"], {"name": "Poison Blade", "description": "Coats the blade in venom.", "damage_type": 7, "power": 18.0, "mana_cost": 8, "cooldown": 1.0, "aoe_radius": 0.0, "required_class": 2, "applies_status": 3, "scaling": {"agility": 0.7}}))
	_add(db, _inst(&"ArrowRain", &"Ability", ["dps", "ranged", "aoe"], {"name": "Arrow Rain", "description": "A volley of arrows over an area.", "damage_type": 0, "power": 22.0, "mana_cost": 14, "cooldown": 6.0, "aoe_radius": 6.0, "required_class": 4, "applies_status": 0, "scaling": {"agility": 0.9}}))
	_add(db, _inst(&"Entangle", &"Ability", ["support", "root"], {"name": "Entangle", "description": "Roots the target in vines.", "damage_type": 7, "power": 8.0, "mana_cost": 12, "cooldown": 4.0, "aoe_radius": 0.0, "required_class": 5, "applies_status": 10, "scaling": {"wisdom": 0.6}}))
	_add(db, _inst(&"RaiseDead", &"Ability", ["summon", "shadow", "ultimate"], {"name": "Raise Dead", "description": "Summons a skeletal minion.", "damage_type": 4, "power": 0.0, "mana_cost": 35, "cooldown": 20.0, "aoe_radius": 0.0, "required_class": 6, "applies_status": 0, "scaling": {"intellect": 1.2}}))
	_add(db, _inst(&"DrainLife", &"Ability", ["dps", "shadow", "lifesteal"], {"name": "Drain Life", "description": "Siphons health from the target.", "damage_type": 4, "power": 26.0, "mana_cost": 16, "cooldown": 2.0, "aoe_radius": 0.0, "required_class": 6, "applies_status": 3, "scaling": {"intellect": 0.9}}))
	_add(db, _inst(&"RustySword", &"Weapon", ["starter", "weapon"], {"name": "Rusty Sword", "rarity": 0, "weapon_type": 0, "damage_type": 0, "base_damage": 8.0, "attack_speed": 1.2, "two_handed": false, "granted_ability": &"", "value": 5}))
	_add(db, _inst(&"IronSword", &"Weapon", ["weapon"], {"name": "Iron Sword", "rarity": 1, "weapon_type": 0, "damage_type": 0, "base_damage": 18.0, "attack_speed": 1.1, "two_handed": false, "granted_ability": &"Slash", "value": 45}))
	_add(db, _inst(&"Flamebrand", &"Weapon", ["fire", "weapon", "unique"], {"name": "Flamebrand", "rarity": 4, "weapon_type": 0, "damage_type": 1, "base_damage": 42.0, "attack_speed": 1.0, "two_handed": true, "granted_ability": &"Fireball", "value": 2500, "is_unique": true, "tint": Color(0.9, 0.4, 0.1), "icon": "res://icon.svg"}))
	_add(db, _inst(&"WarAxe", &"Weapon", ["weapon"], {"name": "War Axe", "rarity": 2, "weapon_type": 1, "damage_type": 0, "base_damage": 30.0, "attack_speed": 0.8, "two_handed": true, "granted_ability": &"Cleave", "value": 280}))
	_add(db, _inst(&"ShadowDagger", &"Weapon", ["shadow", "weapon", "stealth"], {"name": "Shadow Dagger", "rarity": 2, "weapon_type": 3, "damage_type": 4, "base_damage": 24.0, "attack_speed": 1.6, "two_handed": false, "granted_ability": &"Backstab", "value": 320}))
	_add(db, _inst(&"StaffOfWisdom", &"Weapon", ["frost", "weapon"], {"name": "Staff of Wisdom", "rarity": 3, "weapon_type": 7, "damage_type": 2, "base_damage": 12.0, "attack_speed": 0.9, "two_handed": true, "granted_ability": &"Frostbolt", "value": 900}))
	_add(db, _inst(&"NecroWand", &"Weapon", ["shadow", "weapon"], {"name": "Wand of Whispers", "rarity": 3, "weapon_type": 8, "damage_type": 4, "base_damage": 16.0, "attack_speed": 1.3, "two_handed": false, "granted_ability": &"DrainLife", "value": 760}))
	_add(db, _inst(&"HolyMace", &"Weapon", ["holy", "weapon"], {"name": "Dawnbreaker", "rarity": 3, "weapon_type": 2, "damage_type": 5, "base_damage": 28.0, "attack_speed": 1.0, "two_handed": false, "granted_ability": &"Smite", "value": 840}))
	_add(db, _inst(&"HuntingBow", &"RangedWeapon", ["weapon", "ranged"], {"name": "Hunting Bow", "rarity": 1, "weapon_type": 5, "damage_type": 0, "base_damage": 16.0, "attack_speed": 1.2, "two_handed": true, "granted_ability": &"ArrowRain", "value": 60, "range": 24.0, "projectile_speed": 40.0, "spread_degrees": 3.0, "ammo_item": &"WoodArrow"}))
	_add(db, _inst(&"Longbow", &"RangedWeapon", ["weapon", "ranged"], {"name": "Elven Longbow", "rarity": 2, "weapon_type": 5, "damage_type": 0, "base_damage": 26.0, "attack_speed": 1.0, "two_handed": true, "granted_ability": &"ArrowRain", "value": 340, "range": 32.0, "projectile_speed": 52.0, "spread_degrees": 2.0, "ammo_item": &"WoodArrow"}))
	_add(db, _inst(&"Crossbow", &"RangedWeapon", ["weapon", "ranged"], {"name": "Heavy Crossbow", "rarity": 2, "weapon_type": 6, "damage_type": 0, "base_damage": 34.0, "attack_speed": 0.6, "two_handed": true, "granted_ability": &"", "value": 300, "range": 26.0, "projectile_speed": 60.0, "spread_degrees": 1.0, "ammo_item": &"IronBolt"}))
	_add(db, _inst(&"Windforce", &"RangedWeapon", ["weapon", "ranged", "lightning", "unique"], {"name": "Windforce", "rarity": 4, "weapon_type": 5, "damage_type": 3, "base_damage": 44.0, "attack_speed": 1.4, "two_handed": true, "granted_ability": &"ArrowRain", "value": 2800, "range": 40.0, "projectile_speed": 70.0, "spread_degrees": 1.5, "ammo_item": &"WoodArrow"}))
	_add(db, _inst(&"WoodArrow", &"Item", ["ammo", "stackable"], {"name": "Wooden Arrow", "rarity": 0, "value": 1, "weight": 0.05}))
	_add(db, _inst(&"IronBolt", &"Item", ["ammo", "stackable"], {"name": "Iron Bolt", "rarity": 0, "value": 2, "weight": 0.08}))
	_add(db, _inst(&"IronOre", &"Item", ["material", "stackable"], {"name": "Iron Ore", "rarity": 0, "value": 6}))
	_add(db, _inst(&"DragonScale", &"Item", ["material", "rare"], {"name": "Dragon Scale", "rarity": 3, "value": 120, "tint": Color(0.7, 0.1, 0.1)}))
	_add(db, _inst(&"Emberdust", &"Item", ["material", "reagent"], {"name": "Emberdust", "rarity": 2, "value": 40}))
	_add(db, _inst(&"GoldRing", &"Item", ["trinket", "ring"], {"name": "Gold Ring", "rarity": 1, "value": 75}))
	_add(db, _inst(&"ClothRobe", &"Armor", ["chest"], {"name": "Cloth Robe", "rarity": 0, "slot": 3, "material": 0, "armor_value": 4, "resistances": {"FROST": 0.1}, "set_pieces": [], "value": 10}))
	_add(db, _inst(&"LeatherVest", &"Armor", ["chest"], {"name": "Leather Vest", "rarity": 1, "slot": 3, "material": 1, "armor_value": 12, "resistances": {"PHYSICAL": 0.1}, "set_pieces": [], "value": 40}))
	_add(db, _inst(&"LeatherCap", &"Armor", ["head"], {"name": "Leather Cap", "rarity": 1, "slot": 2, "material": 1, "armor_value": 6, "resistances": {"PHYSICAL": 0.05}, "set_pieces": [], "value": 25}))
	_add(db, _inst(&"MailHauberk", &"Armor", ["chest"], {"name": "Mail Hauberk", "rarity": 2, "slot": 3, "material": 2, "armor_value": 22, "resistances": {"PHYSICAL": 0.2, "LIGHTNING": -0.1}, "set_pieces": [], "value": 180}))
	_add(db, _inst(&"PlateGuard", &"Armor", ["chest"], {"name": "Plate Guard", "rarity": 3, "slot": 3, "material": 3, "armor_value": 40, "resistances": {"PHYSICAL": 0.35}, "set_pieces": [], "value": 700}))
	_add(db, _inst(&"DragonHelm", &"Armor", ["head", "dragon", "fire"], {"name": "Dragonscale Helm", "rarity": 4, "slot": 2, "material": 4, "armor_value": 30, "resistances": {"FIRE": 0.5, "FROST": 0.15}, "set_pieces": [&"DragonChest", &"DragonGreaves"], "value": 1400}))
	_add(db, _inst(&"DragonChest", &"Armor", ["chest", "dragon", "fire"], {"name": "Dragonscale Cuirass", "rarity": 4, "slot": 3, "material": 4, "armor_value": 55, "resistances": {"FIRE": 0.6, "PHYSICAL": 0.2}, "set_pieces": [&"DragonHelm", &"DragonGreaves"], "value": 2200}))
	_add(db, _inst(&"DragonGreaves", &"Armor", ["legs", "dragon", "fire"], {"name": "Dragonscale Greaves", "rarity": 4, "slot": 5, "material": 4, "armor_value": 38, "resistances": {"FIRE": 0.5}, "set_pieces": [&"DragonHelm", &"DragonChest"], "value": 1600}))
	_add(db, _inst(&"HealthPotion", &"Consumable", ["potion", "heal"], {"name": "Health Potion", "rarity": 0, "heal_amount": 50, "restores_mana": 0, "applies_status": 0, "duration": 0.0, "stack_size": 20, "value": 8}))
	_add(db, _inst(&"GreaterHealthPotion", &"Consumable", ["potion", "heal"], {"name": "Greater Health Potion", "rarity": 1, "heal_amount": 120, "restores_mana": 0, "applies_status": 0, "duration": 0.0, "stack_size": 10, "value": 30}))
	_add(db, _inst(&"ManaPotion", &"Consumable", ["potion", "mana"], {"name": "Mana Potion", "rarity": 0, "heal_amount": 0, "restores_mana": 40, "applies_status": 0, "duration": 0.0, "stack_size": 20, "value": 8}))
	_add(db, _inst(&"ElixirOfFire", &"Consumable", ["elixir", "fire", "buff"], {"name": "Elixir of Fire", "rarity": 2, "heal_amount": 0, "restores_mana": 0, "applies_status": 1, "duration": 30.0, "stack_size": 5, "value": 60}))
	_add(db, _inst(&"Antidote", &"Consumable", ["potion", "cure"], {"name": "Antidote", "rarity": 0, "heal_amount": 0, "restores_mana": 0, "applies_status": 0, "duration": 0.0, "stack_size": 10, "value": 12}))
	_add(db, _inst(&"HasteDraught", &"Consumable", ["elixir", "buff"], {"name": "Haste Draught", "rarity": 2, "heal_amount": 0, "restores_mana": 0, "applies_status": 9, "duration": 20.0, "stack_size": 5, "value": 55}))
	_add(db, _inst(&"RegenTonic", &"Consumable", ["potion", "buff"], {"name": "Regeneration Tonic", "rarity": 1, "heal_amount": 0, "restores_mana": 0, "applies_status": 6, "duration": 15.0, "stack_size": 10, "value": 35}))
	_add(db, _inst(&"Burn", &"StatusEffectDef", [], {"name": "Burning", "effect": 1, "tick_damage": 6.0, "duration": 4.0, "stacks": true, "modifiers": {"move_speed": -0.1}}))
	_add(db, _inst(&"Chill", &"StatusEffectDef", [], {"name": "Frozen", "effect": 2, "tick_damage": 0.0, "duration": 2.0, "stacks": false, "modifiers": {"attack_speed": -0.4}}))
	_add(db, _inst(&"Venom", &"StatusEffectDef", [], {"name": "Poisoned", "effect": 3, "tick_damage": 4.0, "duration": 6.0, "stacks": true, "modifiers": {}}))
	_add(db, _inst(&"Regeneration", &"StatusEffectDef", [], {"name": "Regeneration", "effect": 6, "tick_damage": -8.0, "duration": 3.0, "stacks": false, "modifiers": {}}))
	_add(db, _inst(&"HolyShield", &"StatusEffectDef", [], {"name": "Shielded", "effect": 7, "tick_damage": 0.0, "duration": 5.0, "stacks": false, "modifiers": {"armor": 20}}))
	_add(db, _inst(&"SkBladework", &"SkillNode", [], {"name": "Bladework", "category": 0, "cost": 1, "prerequisites": [], "grants_ability": &"Slash"}))
	_add(db, _inst(&"SkCleave", &"SkillNode", [], {"name": "Cleaving Strikes", "category": 0, "cost": 2, "prerequisites": [&"SkBladework"], "grants_ability": &"Cleave"}))
	_add(db, _inst(&"SkGuard", &"SkillNode", [], {"name": "Guardian", "category": 1, "cost": 1, "prerequisites": [], "grants_ability": &"ShieldBash"}))
	_add(db, _inst(&"SkPyromancy", &"SkillNode", [], {"name": "Pyromancy", "category": 0, "cost": 2, "prerequisites": [], "grants_ability": &"Fireball"}))
	_add(db, _inst(&"SkInferno", &"SkillNode", [], {"name": "Inferno", "category": 0, "cost": 3, "prerequisites": [&"SkPyromancy"], "grants_ability": &"Blizzard"}))
	_add(db, _inst(&"SkFrost", &"SkillNode", [], {"name": "Cryomancy", "category": 0, "cost": 2, "prerequisites": [], "grants_ability": &"Frostbolt"}))
	_add(db, _inst(&"SkFaith", &"SkillNode", [], {"name": "Faith", "category": 2, "cost": 1, "prerequisites": [], "grants_ability": &"Heal"}))
	_add(db, _inst(&"SkRadiance", &"SkillNode", [], {"name": "Radiance", "category": 2, "cost": 2, "prerequisites": [&"SkFaith"], "grants_ability": &"Bless"}))
	_add(db, _inst(&"SkShadowArts", &"SkillNode", [], {"name": "Shadow Arts", "category": 0, "cost": 2, "prerequisites": [], "grants_ability": &"Backstab"}))
	_add(db, _inst(&"SkNecromancy", &"SkillNode", [], {"name": "Necromancy", "category": 0, "cost": 3, "prerequisites": [&"SkShadowArts"], "grants_ability": &"RaiseDead"}))
	_add(db, _inst(&"GoblinLoot", &"LootTable", [], {"name": "Goblin Loot", "entries": {"RustySword": 40, "HealthPotion": 50, "IronOre": 30}, "guaranteed": [&"HealthPotion"], "gold_min": 2, "gold_max": 12, "rolls": 1}))
	_add(db, _inst(&"BanditLoot", &"LootTable", [], {"name": "Bandit Loot", "entries": {"LeatherVest": 30, "ManaPotion": 40, "GoldRing": 10}, "guaranteed": [], "gold_min": 5, "gold_max": 25, "rolls": 1}))
	_add(db, _inst(&"WraithLoot", &"LootTable", [], {"name": "Wraith Loot", "entries": {"ClothRobe": 35, "ElixirOfFire": 15, "Emberdust": 25}, "guaranteed": [], "gold_min": 8, "gold_max": 30, "rolls": 2}))
	_add(db, _inst(&"DragonLoot", &"LootTable", [], {"name": "Dragon Hoard", "entries": {"Flamebrand": 5, "DragonHelm": 20, "DragonChest": 20, "DragonScale": 60}, "guaranteed": [&"DragonScale"], "gold_min": 200, "gold_max": 600, "rolls": 3}))
	_add(db, _inst(&"ForgeIronSword", &"Recipe", [], {"name": "Forge: Iron Sword", "result": &"IronSword", "ingredients": [&"IronOre"], "quantities": {"IronOre": 3}, "station": 1, "craft_time": 4.0}))
	_add(db, _inst(&"BrewElixirFire", &"Recipe", [], {"name": "Brew: Elixir of Fire", "result": &"ElixirOfFire", "ingredients": [&"Emberdust", &"ManaPotion"], "quantities": {"Emberdust": 2, "ManaPotion": 1}, "station": 2, "craft_time": 3.0}))
	_add(db, _inst(&"CraftDragonHelm", &"Recipe", [], {"name": "Craft: Dragonscale Helm", "result": &"DragonHelm", "ingredients": [&"DragonScale", &"IronOre"], "quantities": {"DragonScale": 5, "IronOre": 4}, "station": 1, "craft_time": 10.0}))
	_add(db, _inst(&"Goblin", &"Enemy", [], {"name": "Goblin Raider", "level": 3, "health": 45, "faction": 4, "behavior": 2, "is_boss": false, "abilities": [&"Slash"], "loot_table": &"GoblinLoot", "tint": Color(0.3, 0.6, 0.2)}))
	_add(db, _inst(&"GoblinShaman", &"Enemy", [], {"name": "Goblin Shaman", "level": 5, "health": 60, "faction": 4, "behavior": 5, "is_boss": false, "abilities": [&"Frostbolt"], "loot_table": &"GoblinLoot", "tint": Color(0.35, 0.7, 0.3)}))
	_add(db, _inst(&"Bandit", &"Enemy", [], {"name": "Bandit", "level": 5, "health": 70, "faction": 3, "behavior": 4, "is_boss": false, "abilities": [&"Backstab"], "loot_table": &"BanditLoot", "tint": Color(0.4, 0.3, 0.25)}))
	_add(db, _inst(&"BanditChief", &"Enemy", [], {"name": "Bandit Chief", "level": 9, "health": 220, "faction": 3, "behavior": 2, "is_boss": true, "abilities": [&"Backstab", &"Cleave"], "loot_table": &"BanditLoot", "tint": Color(0.5, 0.25, 0.2)}))
	_add(db, _inst(&"FrostWraith", &"Enemy", [], {"name": "Frost Wraith", "level": 12, "health": 140, "faction": 4, "behavior": 1, "is_boss": false, "abilities": [&"Frostbolt"], "loot_table": &"WraithLoot", "tint": Color(0.5, 0.7, 0.95)}))
	_add(db, _inst(&"SwampLurker", &"Enemy", [], {"name": "Swamp Lurker", "level": 8, "health": 110, "faction": 4, "behavior": 4, "is_boss": false, "abilities": [&"PoisonBlade", &"Entangle"], "loot_table": &"WraithLoot", "tint": Color(0.3, 0.4, 0.2)}))
	_add(db, _inst(&"Skeleton", &"Enemy", [], {"name": "Risen Skeleton", "level": 6, "health": 55, "faction": 4, "behavior": 2, "is_boss": false, "abilities": [&"Slash"], "loot_table": &"GoblinLoot", "tint": Color(0.8, 0.8, 0.75)}))
	_add(db, _inst(&"Dragon", &"Enemy", [], {"name": "Ancient Dragon", "level": 40, "health": 3200, "faction": 4, "behavior": 2, "is_boss": true, "abilities": [&"Fireball", &"ArrowRain", &"Blizzard"], "loot_table": &"DragonLoot", "tint": Color(0.7, 0.1, 0.1)}))
	_add(db, _inst(&"HeroWarrior", &"Character", [], {"name": "Garruk", "char_class": 0, "starting_weapon": &"IronSword", "starting_abilities": [&"Slash"], "skills": [&"SkBladework", &"SkCleave"], "stats": {"strength": 14, "vitality": 12, "intellect": 6, "agility": 9, "wisdom": 4}}))
	_add(db, _inst(&"HeroMage", &"Character", [], {"name": "Lyra", "char_class": 1, "starting_weapon": &"StaffOfWisdom", "starting_abilities": [&"Fireball", &"Frostbolt"], "skills": [&"SkPyromancy", &"SkFrost"], "stats": {"strength": 5, "vitality": 7, "intellect": 16, "agility": 6, "wisdom": 9}}))
	_add(db, _inst(&"HeroRogue", &"Character", [], {"name": "Vex", "char_class": 2, "starting_weapon": &"ShadowDagger", "starting_abilities": [&"Backstab", &"PoisonBlade"], "skills": [&"SkShadowArts"], "stats": {"strength": 9, "vitality": 8, "intellect": 6, "agility": 15, "wisdom": 5}}))
	_add(db, _inst(&"HeroCleric", &"Character", [], {"name": "Sister Anwen", "char_class": 3, "starting_weapon": &"HolyMace", "starting_abilities": [&"Heal", &"Smite"], "skills": [&"SkFaith", &"SkRadiance"], "stats": {"strength": 7, "vitality": 11, "intellect": 8, "agility": 5, "wisdom": 14}}))
	_add(db, _inst(&"HeroRanger", &"Character", [], {"name": "Kael", "char_class": 4, "starting_weapon": &"Longbow", "starting_abilities": [&"ArrowRain"], "skills": [&"SkShadowArts"], "stats": {"strength": 8, "vitality": 9, "intellect": 7, "agility": 14, "wisdom": 8}}))
	_add(db, _inst(&"HeroNecro", &"Character", [], {"name": "Mortis", "char_class": 6, "starting_weapon": &"NecroWand", "starting_abilities": [&"RaiseDead", &"DrainLife"], "skills": [&"SkNecromancy"], "stats": {"strength": 6, "vitality": 8, "intellect": 15, "agility": 7, "wisdom": 11}}))
	_add(db, _inst(&"AllianceHorde", &"FactionRelation", [], {"faction_a": 0, "faction_b": 1, "standing": -80, "at_war": true, "modifiers": {"trade": -0.5}}))
	_add(db, _inst(&"AllianceMerchants", &"FactionRelation", [], {"faction_a": 0, "faction_b": 5, "standing": 60, "at_war": false, "modifiers": {"trade": 0.2}}))
	_add(db, _inst(&"BanditAll", &"FactionRelation", [], {"faction_a": 3, "faction_b": 0, "standing": -100, "at_war": true, "modifiers": {}}))
	_add(db, _inst(&"ArcaneNeutral", &"FactionRelation", [], {"faction_a": 6, "faction_b": 2, "standing": 20, "at_war": false, "modifiers": {"trade": 0.1}}))
	_add(db, _inst(&"Smith", &"Merchant", [], {"name": "Borin the Smith", "merchant_type": 1, "faction": 5, "inventory": [&"IronSword", &"WarAxe", &"MailHauberk"], "price_overrides": {"IronSword": 40}, "open_hour": 8, "close_hour": 20}))
	_add(db, _inst(&"Alchemist", &"Merchant", [], {"name": "Mira the Alchemist", "merchant_type": 2, "faction": 6, "inventory": [&"HealthPotion", &"ManaPotion", &"ElixirOfFire", &"Antidote"], "price_overrides": {"HealthPotion": 8}, "open_hour": 6, "close_hour": 22}))
	_add(db, _inst(&"Fence", &"Merchant", [], {"name": "Sly Pete", "merchant_type": 4, "faction": 3, "inventory": [&"ShadowDagger", &"GoldRing"], "price_overrides": {}, "open_hour": 20, "close_hour": 4}))
	_add(db, _inst(&"General", &"Merchant", [], {"name": "Tanner's Goods", "merchant_type": 0, "faction": 2, "inventory": [&"WoodArrow", &"IronBolt", &"HealthPotion", &"RustySword"], "price_overrides": {}, "open_hour": 7, "close_hour": 21}))
	_add(db, _inst(&"GoblinMenace", &"Quest", [], {"name": "The Goblin Menace", "quest_type": 1, "giver": &"Goblin", "prerequisite": &"", "reward_item": &"IronSword", "reward_gold": 100, "objectives": PackedStringArray(["Slay 5 goblins", "Report to the captain"]), "stage_flags": {"slay": false, "report": false}, "turn_in_biome": 0}))
	_add(db, _inst(&"BanditTrouble", &"Quest", [], {"name": "Bandit Trouble", "quest_type": 1, "giver": &"BanditChief", "prerequisite": &"GoblinMenace", "reward_item": &"LeatherVest", "reward_gold": 180, "objectives": PackedStringArray(["Clear the bandit camp", "Defeat the Bandit Chief"]), "stage_flags": {"camp": false, "chief": false}, "turn_in_biome": 0}))
	_add(db, _inst(&"FrozenSecrets", &"Quest", [], {"name": "Frozen Secrets", "quest_type": 0, "giver": &"FrostWraith", "prerequisite": &"BanditTrouble", "reward_item": &"StaffOfWisdom", "reward_gold": 400, "objectives": PackedStringArray(["Reach Frozen Peak", "Banish the Frost Wraith"]), "stage_flags": {"reach": false, "banish": false}, "turn_in_biome": 2}))
	_add(db, _inst(&"SlayTheDragon", &"Quest", [], {"name": "Slay the Ancient Dragon", "quest_type": 0, "giver": &"Dragon", "prerequisite": &"FrozenSecrets", "reward_item": &"Flamebrand", "reward_gold": 5000, "objectives": PackedStringArray(["Reach the Volcano", "Defeat the Ancient Dragon"]), "stage_flags": {"reach": false, "slain": false}, "turn_in_biome": 3}))
	_add(db, _inst(&"DailyBounty", &"Quest", [], {"name": "Bounty: Skeletons", "quest_type": 3, "giver": &"Skeleton", "prerequisite": &"", "reward_item": &"HealthPotion", "reward_gold": 30, "objectives": PackedStringArray(["Destroy 10 skeletons"]), "stage_flags": {"count": false}, "turn_in_biome": 4}))
	_add(db, _inst(&"CaptainIntro", &"DialogueNode", [], {"speaker": &"captain_reyes", "text": "The goblins grow bold. Will you help us?", "mood": 0, "responses": {"I'll help.": "CaptainAccept", "Not my problem.": "CaptainRefuse"}, "next_nodes": [&"CaptainAccept", &"CaptainRefuse"], "portrait": "res://icon.svg"}))
	_add(db, _inst(&"CaptainAccept", &"DialogueNode", [], {"speaker": &"captain_reyes", "text": "Bless you, traveler. Clear the forest.", "mood": 5, "responses": {}, "next_nodes": []}))
	_add(db, _inst(&"CaptainRefuse", &"DialogueNode", [], {"speaker": &"captain_reyes", "text": "Then we are doomed...", "mood": 3, "responses": {}, "next_nodes": []}))
	_add(db, _inst(&"MiraGreet", &"DialogueNode", [], {"speaker": &"mira_alchemist", "text": "Fresh potions! What do you need?", "mood": 0, "responses": {"Show me your wares.": "MiraShop", "Just browsing.": ""}, "next_nodes": [&"MiraShop"]}))
	_add(db, _inst(&"MiraShop", &"DialogueNode", [], {"speaker": &"mira_alchemist", "text": "Everything's fairly priced, I assure you.", "mood": 0, "responses": {}, "next_nodes": []}))
	_add(db, _inst(&"DarkForest", &"Zone", [], {"name": "Darkwood Forest", "biome": 0, "min_level": 1, "max_level": 8, "merchants": [&"General", &"Smith"], "ambient_color": Color(0.2, 0.3, 0.2)}))
	_add(db, _inst(&"FrozenPeak", &"Zone", [], {"name": "Frozen Peak", "biome": 2, "min_level": 10, "max_level": 18, "merchants": [&"Alchemist"], "ambient_color": Color(0.6, 0.7, 0.9)}))
	_add(db, _inst(&"DragonsLair", &"Zone", [], {"name": "Dragon's Lair", "biome": 3, "min_level": 35, "max_level": 45, "merchants": [], "ambient_color": Color(0.8, 0.2, 0.1)}))
	_add(db, _inst(&"Thornmarsh", &"Zone", [], {"name": "Thornmarsh", "biome": 5, "min_level": 6, "max_level": 14, "merchants": [&"Fence"], "ambient_color": Color(0.25, 0.35, 0.22)}))
	_add(db, _inst(&"FirstBlood", &"Achievement", [], {"title": "First Blood", "description": "Defeat your first enemy.", "points": 10, "hidden": false, "reward_item": &"HealthPotion", "required_quest": &""}))
	_add(db, _inst(&"DragonSlayer", &"Achievement", [], {"title": "Dragonslayer", "description": "Defeat the Ancient Dragon.", "points": 100, "hidden": false, "reward_item": &"DragonScale", "required_quest": &"SlayTheDragon"}))
	_add(db, _inst(&"Collector", &"Achievement", [], {"title": "Collector", "description": "Own one item of every rarity.", "points": 50, "hidden": true, "reward_item": &"GoldRing", "required_quest": &""}))

func _add(db: PatternDatabaseFile, p: PdbPattern) -> void:
	db.patterns[p.id] = p

func _enum(id: StringName, tag: String, desc: String, values: Dictionary) -> PdbEnum:
	var e := PdbEnum.new()
	e.id = id
	if tag != "": e.add_tag(tag)
	e.description = desc
	e.values = values
	return e

func _const(id: StringName, tag: String, desc: String, data: Dictionary) -> PdbConst:
	var c := PdbConst.new()
	c.id = id
	if tag != "": c.add_tag(tag)
	c.description = desc
	c.data = data
	return c

func _field(fname: StringName, ftype: int, hint: int = PROPERTY_HINT_NONE, hint_string: String = "", group: String = "", desc: String = "", required: bool = false, default = null) -> PdbFieldDefinition:
	var f := PdbFieldDefinition.new()
	f.field_name = fname
	f.field_type = ftype
	f.hint = hint
	f.hint_string = hint_string
	f.export_group = group
	f.description = desc
	f.required = required
	f.default_value = default
	return f

func _def(id: StringName, tag: String, desc: String, extends_type: String, icon: String, fields: Array) -> PdbModelDefinition:
	var d := PdbModelDefinition.new()
	d.id = id
	if tag != "": d.add_tag(tag)
	d.description = desc
	d.extends_type = extends_type
	d.icon_name = icon
	d.fields.assign(fields)
	return d

func _inst(id: StringName, def_id: StringName, tags: Array, data: Dictionary) -> PdbModelInstance:
	var i := PdbModelInstance.new()
	i.id = id
	i.definition_id = def_id
	for t in tags:
		if t != "":
			i.add_tag(t)
	i.data = data
	return i
